stages:
  - plan
  - apply
  - destroy

variables:
  TF_VERSION: "1.9.5"
  AWS_REGION: "us-east-1"

before_script:
  - apt-get update && apt-get install -y unzip curl python3-pip git
  - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform.zip && mv terraform /usr/local/bin/
  - terraform -version
  - pip install awscli
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_REGION}
  - git clone https://oauth2:${GITHUB_TOKEN}@github.com/<SEU_USUARIO>/<SEU_REPOSITORIO>.git terraform-code
  - cd terraform-code

plan:
  stage: plan
  script:
    - cd terraform-code
    - terraform init
    - terraform validate
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - terraform-code/tfplan
  when: manual
  only:
    - main

apply:
  stage: apply
  script:
    - cd terraform-code
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  when: manual
  only:
    - main

destroy:
  stage: destroy
  script:
    - cd terraform-code
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  only:
    - main
