image: hashicorp/terraform:1.9.5

stages:
  - plan
  - apply
  - destroy

variables:
  AWS_DEFAULT_REGION: "us-east-1"

cache:
  paths:
    - .terraform/

before_script:
  - terraform --version
  - terraform init

plan:
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - tfplan
    expire_in: 20 mins 
  only:
    - main

apply:
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  when: manual
  only:
    - main

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  only:
    - main